### ISSUE TITLE
parsing config file

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/webserv#22]
- [ ] 1. Format YAML only
- [ ] 2. Only 2 spaces separator
- [x] 3. First range only `server` keywords
- [ ] 4. Second range only `body_max`, `routes` and `error_page` keywords
- [ ] 5. `body_max` can only be number between 100 and 1000 (for example)
- [ ] 6. `error_page` can only have number as range limited to: 401, 402, 403, 500 (for example)
- [ ] 7. `routes` key word can only have `endpoint`, `type`, `server_name`, `port`, `folder`, `directory_listing`, `file_if_is_repository` and `extenion_for_cgi` as child keywords.
- [ ] 8. `endpoint` keyword can only start by `/` and only contain char, `/`, and `.`
- [ ] 9. `type` keyword are string separated by `,`, spaces are deleted array can only contain string with value `GET`, `POST` and `DELETE`.
- [ ] 10. `server_name` can only be a string with char only
- [ ] 11. `port` can only be string between `1000` and `9000` (for example)
- [ ] 12. `folder` keyword can only start by `/` and only contain char, and `.`
- [ ] 13. `directory_listing` can only container `true` and `false`
- [ ] 14. `file_if_is_repertory` keyword can only start by `/` and only contain char, and `.`
- [ ] 15. `extention_for_cgi` can only be string, started by `dot`, separae by `,` and spaces are deleted

**Comment by S-Stanley** [comment]
```
server:
  body_max: 150
  error_page:
    404: /www/error/404.html
    403: /www/error/403.html
  routes:
    endpoint: /
    type: GET, POST
    server_name: localhost
    port: 8080
    folder: /www
    directory_listing: true
    file_if_is_repertory: /www/index.html
    extention_for_cgi: .php, .pdf
server:
  routes:
    endpoint: /data/file
    type: GET, POST, DELETE
    folder: /www/data/file
    download: true
```
